
<script>
    import CurrentFrame from "$lib/stores/CurrentFrame";
    import CreateFrame from "../lib/frames/CreateFrame.svelte";
    import PlayFrame from "../lib/frames/PlayFrame.svelte";
    import DoneFrame from "../lib/frames/DoneFrame.svelte";
    import HomeFrame from "../lib/frames/HomeFrame.svelte";
    import ShowLoader from '$lib/stores/ShowLoader';
    import PostData from "$lib/stores/PostData";
    import General from "$lib/stores/General";
    import { setContext } from 'svelte';
    import { fade, scale } from "svelte/transition";
    import LeaderBoard from "$lib/stores/LeaderBoard";

    $ShowLoader = true;

    let messageOutput = '';
    let mounted = false;
    let isReinit = false;


    const handleMessage = (ev) => {
        const { type, data } = ev.data;

        if (type === 'devvit-message') {
            const { message } = data;
            // Always output full message
            messageOutput = JSON.stringify(message, undefined, 2);

            // Load initial data
            if (message.type === 'initialData') {

                if(mounted && !isReinit) return;

              
                $General.userName = message?.data?.username;
                $CurrentFrame = "home" 
                $General.mode = "home";
                console.log("var updated")  
          

                if (message?.data?.isGameData){
                    $PostData = message?.data?.postData || {};
                    if (message?.data?.isCreator) {
                        $CurrentFrame = "done" 
                        $General.mode = "done";
                        $PostData.isCreator= true
                        $PostData.doneTangle = $PostData?.tangle;
                    }else{
                        $CurrentFrame = "play" 
                        $General.mode = "play";
                        
                        if (message?.data?.parsedDoneGame?.doneTangle && message?.data?.parsedDoneGame?.doneTangle?.length > 0){
                            $PostData.doneTangle = message?.data?.parsedDoneGame?.doneTangle;
                            $PostData.doneTime = message?.data?.parsedDoneGame?.doneTime;
                            $LeaderBoard = message?.data?.parsedLeaderBoard || [];
                            $CurrentFrame = "done" 
                            $General.mode = "done";
                        }
                    }
                } 
                    
                    
                mounted = true;
                isReinit = false;
                $ShowLoader = false;

            }else if (message.type === 'refresh'){
                refreshData()
            }
        }
    };

    const refreshData = () => {
        isReinit = true;
        window.parent.postMessage({
            type: 'webViewReady'
        }, '*');

    }

    setContext('refreshData', refreshData);


    if (import.meta.env.PROD) {
        console.log("This is production build!");
        const interval = setInterval(() => {
            if (!mounted) {
                window.parent.postMessage({
                    type: 'webViewReady'
                }, '*');
            } else {
                clearInterval(interval); // Stop the interval once mounted is true
            }
        }, 500); 
    }else{
        console.log("This is development build!");
        mounted = true;
        $ShowLoader = false;
    }


</script>

<svelte:window on:message={handleMessage}/>


{#if $ShowLoader}
    <div transition:fade class="z-[9999] w-full h-screen fixed top-0 left-0 bg-black flex justify-center items-center font-inter-italic uppercase font-bold text-[1.5em]">
        <div class="w-2em" transition:scale>
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="shape-rendering: auto; display: block; background: transparent;"><g><circle stroke-dasharray="164.93361431346415 56.97787143782138" r="35" stroke-width="10" stroke="#fff" fill="none" cy="50" cx="50">
                <animateTransform keyTimes="0;1" values="0 50 50;360 50 50" dur="1s" repeatCount="indefinite" type="rotate" attributeName="transform"/>
            </circle><g/></g><!-- [ldio] generated by https://loading.io --></svg>
        </div>
    </div>
{/if}

<div class="bg-no-repeat bg-cover flex justify-center items-center h-screen w-full">
    
    
    {#if $CurrentFrame == 'home'}
        <HomeFrame/>
    {:else if $CurrentFrame == 'create'}
        <CreateFrame/>
    {:else if $CurrentFrame == 'play'}
        <PlayFrame/>
    {:else if $CurrentFrame == 'done'}
        <DoneFrame/>

    <!-- {:else if $CurrentFrame == 'history'}
        <HistoryFrame/>
    {:else if $CurrentFrame == 'treasure'}
        <TreasureFrame/>
    {:else if $CurrentFrame == 'howToPlay'}
        <HowToPlayFrame/> -->
    {/if}


    
</div>



<!-- <pre class="text-[0.8em] bg-gray-200 text-black p-0hem rounded overflow-auto max-h-[15em]">
    output: 
    {messageOutput}
</pre> -->


